rilling/OSMDashboardConcordia

build.gradle
src/main/java/de/storchp/opentracks/osmplugin/dashboardapi/APIConstants.java

**Link To the Issue**
[Issue 9](https://github.com/rilling/OSMDashboardConcordia/issues/9)

Resolved Issue #9 by adding a private constructor to the API Constants Utility class

---

src/main/java/de/storchp/opentracks/osmplugin/maps/StyleColorCreator.java

https://github.com/rilling/OSMDashboardConcordia/issues/12

Resolution: Fix Sonar Issue: Missing default clause to the switch statement

---

build.gradle
src/main/java/de/storchp/opentracks/osmplugin/compass/AbstractLowPassSensor.java

Fix abstract class visibility

---

src/main/java/de/storchp/opentracks/osmplugin/compass/SensorChecker.java

Added a private constructor to hide the implicit public one.

Added a Private constructor to hide the implicit public one

---

build.gradle
src/main/java/de/storchp/opentracks/osmplugin/BaseActivity.java

Refactor the code

---

build.gradle
src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java

Refactored method onCreate to reduce its Cognitive Complexity.

---

src/main/java/de/storchp/opentracks/osmplugin/compass/AbstractLowPassSensor.java

Add a nested comment explaining why onAccuracyChanged method is empty

---

src/main/java/de/storchp/opentracks/osmplugin/compass/Compass.java

Modified UpdateSensor Method

---

src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java

Code Smell Fix: Fix view paramater issue

---

src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java

Use isEmpty() to check whether the collection is empty or not.

---

src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java

removed unnecessary null check

---

src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java

removing unnecessary null check

---

src/main/java/de/storchp/opentracks/osmplugin/compass/Compass.java

This will resolve an issue #51

Compass Refactoring

---

src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java

Either remove or fill this block of code.

---

src/main/java/de/storchp/opentracks/osmplugin/BaseActivity.java
src/main/java/de/storchp/opentracks/osmplugin/DownloadActivity.java
src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java

Merging all changes of group-12
Issues: #1 #2 #3 #4 #7 #8

Merge Group 12 Changes

---

src/main/java/de/storchp/opentracks/osmplugin/utils/PreferencesUtils.java

Solving code smell generated from issue

---

src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
src/main/res/layout/map.xml

Issue:- Maps are missing a legend. It is not clear what are the different colors of the tracks - what are they correlating to?
Solution:- When using the 'Color by speed' option in user settings. The polyline on the map will be colored according to below criteria,
Speed = 0, polyline would be green
Speed < Avg speed, polyline would be yellow
Speed < Avg speed, polyline would be orange
Avgspeed< Speed <Max Speed, polyline would be blue
Speed = MaxSpeed, polyline would be red.
A legend would be shown which would reflect the information stated above, with some text data included as well.

Enhancement - Issue#67 (Maps are missing a legend)

---

src/main/res/values/strings.xml

Solves Issue #92 - Created a string for strings.xml that was necessary to add average speed in km/h.

Solves Issue #92

---

src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java

feat: Add support for rendering different layers

---

src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
src/main/res/layout/map.xml

Implemented the requested enhancement. Changes were made to the below files
**src/main/java/de/storchp/opentracks/osmplugin/MapsActivity.java
src/main/res/layout/map.xml**
Details [here](https://github.com/rilling/OSMDashboardConcordia/issues/67)

Issue #67 - Maps are missing a legend.
